apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: your-docker-registry/inventory-service:latest
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: ecom-config
            - secretRef:
                name: ecom-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
