apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: your-docker-registry/product-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: ecom-config
            - secretRef:
                name: ecom-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
